services:
  - type: web
    name: issue-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn routes:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: issue_tracker_db
          property: connectionString

databases:
  - name: issue_tracker_db
    databaseName: issue_tracker
    plan: free 